### ISSUE TITLE
Update fail: New ChEBI source files

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/grounding-search#67]
Error encountered in update from ChEBI when applied to download (ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl.gz). 

Reproduce: 
- delete chebi data file (`/input/chebi.owl`)
- `npm run update:chebi`  

Console out:
```
info:    Applying update on source 'chebi'...
info:    Downloading ftp://ftp.ebi.ac.uk/pub/databases/chebi/ontology/chebi.owl.gz to chebi.owl
info:    Processing chebi data from input/chebi.owl
TypeError: Cannot read property 'replace' of undefined
    at processEntry (.../grounding-search/src/server/datasource/chebi.js:64:43)
    at Array.map (<anonymous>)
    at .../grounding-search/src/server/datasource/processing.js:11:34    
  ...
```

Other:
  - The fail above left the index in a semi-complete state: some chemicals but nothing from ncbi

**Comment by jvwong** [comment]
At least one issue are 'preliminary entries' like:
```xml
<owl:Class rdf:about="https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:43262">
```
Which points to a [4,5-DEHYDRO-D-GLUCURONIC ACID](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:43262) 

Anyways, maybe we just need to skip over things like this, to prevent this single point of failure.
